package co.claro.adapter.consultasaldo.constant;

public class Examples {

	public Examples() {
		throw new UnsupportedOperationException("Utility class");
	}


	public static final String REQUEST_EXAMPLE = "{\n"
			+ "  \"header\": {\n"
			+ "    \"messageID\": \"KCB_MESSAGEID\",\n"
			+ "    \"featureCode\": \"101\",\n"
			+ "    \"featureName\": \"FinancialInquiries\",\n"
			+ "    \"serviceCode\": \"1003\",\n"
			+ "    \"serviceName\": \"BalanceInquiry\",\n"
			+ "    \"serviceSubCategory\": \"ACCOUNT\",\n"
			+ "    \"minorServiceVersion\": \"1.0\",\n"
			+ "    \"channelCode\": \"101\",\n"
			+ "    \"channelName\": \"atm\",\n"
			+ "    \"routeCode\": \"001\",\n"
			+ "    \"routeName\": \"t24\",\n"
			+ "    \"processingCode\": \"1002\",\n"
			+ "    \"timeStamp\": \"22222\",\n"
			+ "    \"serviceMode\": \"sync\",\n"
			+ "    \"subscribeEvents\": \"1\",\n"
			+ "    \"callBackURL\": \"\"\n"
			+ "  },\n"
			+ "  \"requestPayload\": {\n"
			+ "    \"primaryData\": {\n"
			+ "      \"businessKey\": \"9940000057\",\n"
			+ "      \"businessKeyType\": \"AccountNumber\"\n"
			+ "    },\n"
			+ "    \"additionalData\": {\n"
			+ "      \"companyCode\": \"RW9990001\",\n"
			+ "      \"sessionID\": \"9940000057\",\n"
			+ "      \"rrn\": \"YT90932\",\n"
			+ "      \"uniqueRef\": \"PSAE76420\"\n"
			+ "    }\n"
			+ "  }\n"
			+ "}";
	
	public static final String RESPONSE_OK =  "{\n"
			+ "  \"header\": {\n"
			+ "    \"messageID\": \"KCB_MESSAGEID\",\n"
			+ "    \"conversationID\": \"50697c9c-e129-4071-b323-a6640296fee1\",\n"
			+ "    \"targetSystemID\": \"not available\",\n"
			+ "    \"channelCode\": \"101\",\n"
			+ "    \"channelName\": \"atm\",\n"
			+ "    \"routeCode\": \"001\",\n"
			+ "    \"routeName\": \"t24\",\n"
			+ "    \"serviceCode\": \"1011002\",\n"
			+ "    \"processingCode\": \"1002\",\n"
			+ "    \"statusCode\": \"0\",\n"
			+ "    \"statusDescription\": \"Success\",\n"
			+ "    \"ehfInfo\": {\n"
			+ "      \"item\": [\n"
			+ "        {\n"
			+ "          \"ehfRef\": \"OSP-1002\",\n"
			+ "          \"ehfDesc\": \"Processed Successfully\"\n"
			+ "        }\n"
			+ "      ]\n"
			+ "    }\n"
			+ "  },\n"
			+ "  \"responsePayload\": {\n"
			+ "    \"primaryData\": {\n"
			+ "      \"businessKey\": \"9940000057\",\n"
			+ "      \"businessKeyType\": \"AccountNumber\"\n"
			+ "    },\n"
			+ "    \"additionalData\": {\n"
			+ "      \"accountNumber\": \"9940000057\",\n"
			+ "      \"uniqueRef\": \"PSAE76420\",\n"
			+ "      \"sessionID\": \"20226510\",\n"
			+ "      \"ledgerBalance\": \"544739.61\",\n"
			+ "      \"netBalance\": \"544739.61\",\n"
			+ "      \"rrn\": \"YT90932\"\n"
			+ "    }\n"
			+ "  }\n"
			+ "}";

	public static final String RESPONSE_NOT_OK = "{\n"
			+ "  \"header\": {\n"
			+ "    \"messageID\": \"KCB_MESSAGEID\",\n"
			+ "    \"conversationID\": \"50697c9c-e129-4071-b323-a6640296fee1\",\n"
			+ "    \"targetSystemID\": \"not available\",\n"
			+ "    \"channelCode\": \"101\",\n"
			+ "    \"channelName\": \"atm\",\n"
			+ "    \"routeCode\": \"001\",\n"
			+ "    \"routeName\": \"t24\",\n"
			+ "    \"statusCode\": \"06\",\n"
			+ "    \"statusDescription\": \"Error\",\n"
			+ "    \"ehfInfo\": {\n"
			+ "      \"item\": [\n"
			+ "        {\n"
			+ "          \"ehfRef\": \"Dynamically Generated\",\n"
			+ "          \"ehfDesc\": \"Dynamicall Generated\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "          \"ehfRef\": \"Dynamically Generated\",\n"
			+ "          \"ehfDesc\": \"Dynamicall Generated\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "          \"ehfRef\": \"Dynamically Generated\",\n"
			+ "          \"ehfDesc\": \"Dynamicall Generated\"\n"
			+ "        }\n"
			+ "      ]\n"
			+ "    }\n"
			+ "  },\n"
			+ "  \"responsePayload\": {\n"
			+ "    \"primaryData\": {\n"
			+ "      \"businessKey\": \"9940000057\",\n"
			+ "      \"businessKeyType\": \"AccountNumber\"\n"
			+ "    }\n"
			+ "  }\n"
			+ "}";

	public static final String T24_SUCCESSFUL_RESPONSE = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
			+ "<S:Envelope xmlns:S=\"http://schemas.xmlsoap.org/soap/envelope/\">\n"
			+ "	<S:Body>\n"
			+ "		<ns3:BalanceEnquiryWebserviceResponse xmlns:ns2=\"http://temenos.com/KCBRWATMBALENQ\" xmlns:ns3=\"http://temenos.com/BAL.ENQATM\">\n"
			+ "			<Status>\n"
			+ "				<successIndicator>Success</successIndicator>\n"
			+ "			</Status>\n"
			+ "			<KCBRWATMBALENQType>\n"
			+ "				<ns2:gKCBRWATMBALENQDetailType>\n"
			+ "					<ns2:mKCBRWATMBALENQDetailType>\n"
			+ "						<ns2:ACCOUNTNO>9940000057</ns2:ACCOUNTNO>\n"
			+ "						<ns2:SERVICECODE>1011002</ns2:SERVICECODE>\n"
			+ "						<ns2:CHANNELCODE>101</ns2:CHANNELCODE>\n"
			+ "						<ns2:UNIQUEREF>PSAE76420</ns2:UNIQUEREF>\n"
			+ "						<ns2:SESSIONID>20226510</ns2:SESSIONID>\n"
			+ "						<ns2:LedgerBalance>544739.61</ns2:LedgerBalance>\n"
			+ "						<ns2:NetBalance>544739.61</ns2:NetBalance>\n"
			+ "						<ns2:Rrn>YT90932</ns2:Rrn>\n"
			+ "					</ns2:mKCBRWATMBALENQDetailType>\n"
			+ "				</ns2:gKCBRWATMBALENQDetailType>\n"
			+ "			</KCBRWATMBALENQType>\n"
			+ "		</ns3:BalanceEnquiryWebserviceResponse>\n"
			+ "	</S:Body>\n"
			+ "</S:Envelope>";
	
	public static final String T24_ERROR_RESPONSE = "<?xml version='1.0' encoding='UTF-8'?>\n"
			+ "<S:Envelope\n"
			+ "	xmlns:S=\"http://schemas.xmlsoap.org/soap/envelope/\">\n"
			+ "	<S:Body>\n"
			+ "		<ns10:BalanceEnquiryWebserviceResponse\n"
			+ "			xmlns:ns2=\"http://temenos.com/KCBRWATMBALENQ\"\n"
			+ "			xmlns:ns3=\"http://temenos.com/FUNDSTRANSFERKCBMERCHANTPOS\"\n"
			+ "			xmlns:ns4=\"http://temenos.com/FUNDSTRANSFER\"\n"
			+ "			xmlns:ns5=\"http://temenos.com/FUNDSTRANSFERKCBGENERIC\"\n"
			+ "			xmlns:ns6=\"http://temenos.com/FUNDSTRANSFERKCBATMDEPOSIT\"\n"
			+ "			xmlns:ns7=\"http://temenos.com/FUNDSTRANSFERKCBREVERSAL\"\n"
			+ "			xmlns:ns8=\"http://temenos.com/KCBRWATMMINISTMT\"\n"
			+ "			xmlns:ns9=\"http://temenos.com/FUNDSTRANSFERKCBATMCASHWITHDR\"\n"
			+ "			xmlns:ns10=\"http://temenos.com/ATM.SERVICES\">\n"
			+ "			<Status>\n"
			+ "				<successIndicator>T24Error</successIndicator>\n"
			+ "				<messages>ACCOUNTAccountNo/WRK.BALLedgerBalance/NET.BALNetBalance/CURRENCYCurrency/ACCOUNT.TITLE.1AccountTitle/ACCOUNT.STATUSAccountStatus</messages>\n"
			+ "				<messages>No records were found that matched the selection criteria</messages>\n"
			+ "				<messages>Bucket Error E-130310</messages>\n"
			+ "			</Status>\n"
			+ "		</ns10:BalanceEnquiryWebserviceResponse>\n"
			+ "	</S:Body>\n"
			+ "</S:Envelope>";

}
