spring:
  profiles:
    active: default
info:
  app:
    name: adapter-consulta-saldo
    description: 'This service will obtain various balances viz., account'
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: info,health,camelroutes
    enabled-by-default: 'true'
  server:
    port: '8080'
  security:
    enabled: false
camel:
  servlet:
    mapping:
      context-path: /api/*
      servlet-name: CamelServlet
      enabled: 'true'
  springboot:
    name: consulta-saldo
    main-run-controller: 'true'
    jmx-enabled: 'true'
server:
  port: 8080
# #logging configuration path
logging:
  config: classpath:logback.xml
amq:
  logging:
    component: amqp
    topic: "001.CONSULTA.SALDO.TOPIC"

camelComponent: servlet

atomic:
  protocol: http
  host: localhost
  port: 8080
  path: /api/be/consultaSaldoAtomic
  method: POST
  uri-params: "?bridgeEndpoint=true&httpMethod=${atomic.method}&throwExceptionOnFailure=false"
  uri: ${atomic.protocol}://${atomic.host}:${atomic.port}${atomic.path}${atomic.uri-params}
---
spring:
  profiles: local
  
# spring boot management server instance properties
management:
  server:
    port: 8081
    
# spring boot server instance properties
server:
  port: 8081

atomic:
  port: 8082
---